name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 11076708 # Android 13

      - name: Build reference documentation
        run: ./gradlew dokkaHtmlMultiModule

      - name: Copy reference documentation to docusaurus
        run: cp -r build/dokka/htmlMultiModule/* docs/static/reference/

      - name: Build docs
        run: |
          npm install
          npm run build
        working-directory: ./docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build # The folder the action should deploy.
